### PR TITLE
Added support for generic types to be registered as tables.

### PR DESCRIPTION
**Pull request by jpduarte-insureon**

### CODE REVIEW

**Comment by mythz** [comment]
Thx for the PR! 

Can you also [approve the Contributor License Agreement](https://docs.google.com/forms/d/16Op0fmKaqYtxGL4sg7w_g-cXXyCoWjzppgkuqzOeKyk/viewform) so we can merge this, thx.

**Comment by jpduarte-insureon** [comment]
I've approved the Contribute License Agreement. The PR doesn't break any tests.

**Comment by mythz** [comment]
Cheers :+1: 

FYI, this change is available from v4.0.55 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by jpduarte-insureon** [comment]
Sweet! You guys are awesome.

**Pull request merged**
